apiVersion: openstack.taikun.cloud/v1alpha1
kind: OpenStackSRE
metadata:
  labels:
    app.kubernetes.io/name: openstack-sre-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstacksre-sample
spec:
  # TODO(user): Add fields here
